### ISSUE TITLE
How should I best cite this repo?

### ISSUE THREAD

**Issue by williamgilpin** [wiskott-lab/sklearn-sfa#6]
Hello, I am curious about your preferred way that I cite this repo in a paper. I am currently using the following:

```
@article{wiskott2002slow,
  title={Slow feature analysis: Unsupervised learning of invariances},
  author={Wiskott, Laurenz and Sejnowski, Terrence J},
  journal={Neural computation},
  volume={14},
  number={4},
  pages={715--770},
  year={2002},
  publisher={MIT Press}
}
```

Please let me know if there is another reference that you would prefer I cited. Thanks very much for this excellent code!

**Comment by Stewori** [comment]
If you want to cite a code repository specifically or in addition to the paper of the algorithm, note that it is well possible to cite web resources/urls, `github.com/wiskott-lab/sklearn-sfa` in this case. Not the preferred kind of citation I agree, but definitely an option. For bibtex, online resources should be cited using a `@misc` entry and the access date should be included, see the discussion on https://tex.stackexchange.com/questions/3587/how-can-i-use-bibtex-to-cite-a-web-page.

**Comment by williamgilpin** [comment]
Sounds good, I'll cite the repository directly! Thank you very much, and have a great holidays!
